In [74]:
# this eda is important for preparing date and time columns
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 

import warnings
warnings.filterwarnings('ignore')

In [75]:
data = pd.read_excel("flight_price.xlsx")
data

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302
...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,9/04/2019,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107
10679,Air India,27/04/2019,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145
10680,Jet Airways,27/04/2019,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229
10681,Vistara,01/03/2019,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648
10682,Air India,9/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753

Description:
The various features of the data are explained below:

1. Airline: The name of the airline company is stored in the airline column. It is a categorical feature having 6 different airlines.
2. source: City from which the flight takes off. It is a catrgorical data having 6 unique cities
3. stops: A categorical feature with 3 distinct values that stores the number of stops b/w the source and destination cities
4. Arrival Time: This is a derived categorical feature created by grouping time intervals into bins. It has six distinct time labels and keep information about the arrival time.
5. Destination: City where the flight will land. It is a categorical feature having 6 unique cities.
6. Duration: A continuous feature that displays the overall amount of time it takes to travel between cities in hours.
7. Price: Target variable stores information of the ticket price.

In [76]:
data.shape

(10683, 11)

In [77]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
dtypes: int64(1), object(10)
memory usage: 918.2+ KB

In [78]:
data.dtypes

Airline            object
Date_of_Journey    object
Source             object
Destination        object
Route              object
Dep_Time           object
Arrival_Time       object
Duration           object
Total_Stops        object
Additional_Info    object
Price               int64
dtype: object

In [79]:
data.isnull().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              1
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        1
Additional_Info    0
Price              0
dtype: int64

Routes has null values 
#As per our understanding a flight cannot go from one place to another without taking route -->
so drop null values

In [80]:
data.dropna(axis = 0, inplace=True)

In [81]:
data.isnull().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              0
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        0
Additional_Info    0
Price              0
dtype: int64

In [82]:
data.columns

Index(['Airline', 'Date_of_Journey', 'Source', 'Destination', 'Route',
       'Dep_Time', 'Arrival_Time', 'Duration', 'Total_Stops',
       'Additional_Info', 'Price'],
      dtype='object')

In [83]:
data.Date_of_Journey

0        24/03/2019
1         1/05/2019
2         9/06/2019
3        12/05/2019
4        01/03/2019
            ...
10678     9/04/2019
10679    27/04/2019
10680    27/04/2019
10681    01/03/2019
10682     9/05/2019
Name: Date_of_Journey, Length: 10682, dtype: object

In [84]:
"Harshada/Chaudhari".split("/")[1]

'Chaudhari'

In [85]:
data["days"] = data.Date_of_Journey.str.split("/").str[0]  #days
data["months"] = data.Date_of_Journey.str.split("/").str[1]  #months
data["years"] = data.Date_of_Journey.str.split("/").str[2]  #years

In [86]:
data

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,days,months,years
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,03,2019
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,05,2019
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,9,06,2019
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,12,05,2019
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,01,03,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,9/04/2019,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107,9,04,2019
10679,Air India,27/04/2019,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145,27,04,2019
10680,Jet Airways,27/04/2019,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229,27,04,2019
10681,Vistara,01/03/2019,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648,01,03,2019
10682,Air India,9/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753,9,05,2019

In [87]:
data.dtypes

Airline            object
Date_of_Journey    object
Source             object
Destination        object
Route              object
Dep_Time           object
Arrival_Time       object
Duration           object
Total_Stops        object
Additional_Info    object
Price               int64
days               object
months             object
years              object
dtype: object

In [88]:
data['days'] = data.days.astype(int)
data['months'] = data.months.astype(int)
data['years'] = data.years.astype(int)

In [89]:
data.dtypes

Airline            object
Date_of_Journey    object
Source             object
Destination        object
Route              object
Dep_Time           object
Arrival_Time       object
Duration           object
Total_Stops        object
Additional_Info    object
Price               int64
days                int32
months              int32
years               int32
dtype: object

In [90]:
data.drop('Date_of_Journey',axis=1, inplace=True)
data

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,days,months,years
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,3,2019
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,5,2019
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,9,6,2019
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,12,5,2019
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,1,3,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107,9,4,2019
10679,Air India,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145,27,4,2019
10680,Jet Airways,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229,27,4,2019
10681,Vistara,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648,1,3,2019
10682,Air India,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753,9,5,2019

In [91]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10682 entries, 0 to 10682
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10682 non-null  object
 1   Source           10682 non-null  object
 2   Destination      10682 non-null  object
 3   Route            10682 non-null  object
 4   Dep_Time         10682 non-null  object
 5   Arrival_Time     10682 non-null  object
 6   Duration         10682 non-null  object
 7   Total_Stops      10682 non-null  object
 8   Additional_Info  10682 non-null  object
 9   Price            10682 non-null  int64
 10  days             10682 non-null  int32
 11  months           10682 non-null  int32
 12  years            10682 non-null  int32
dtypes: int32(3), int64(1), object(9)
memory usage: 1.0+ MB

In [92]:
data.Arrival_Time

0        01:10 22 Mar
1               13:15
2        04:25 10 Jun
3               23:30
4               21:35
             ...
10678           22:25
10679           23:20
10680           11:20
10681           14:10
10682           19:15
Name: Arrival_Time, Length: 10682, dtype: object

In [93]:
data['Arrival_Time'].apply(lambda x:x.split(" "))
# you only want time i.e., is 0th element

0        [01:10, 22, Mar]
1                 [13:15]
2        [04:25, 10, Jun]
3                 [23:30]
4                 [21:35]
               ...
10678             [22:25]
10679             [23:20]
10680             [11:20]
10681             [14:10]
10682             [19:15]
Name: Arrival_Time, Length: 10682, dtype: object

In [94]:
data['Arrival_Time']=data['Arrival_Time'].apply(lambda x:x.split(" ")[0])

In [95]:
data['Arrival_Time']

0        01:10
1        13:15
2        04:25
3        23:30
4        21:35
         ...
10678    22:25
10679    23:20
10680    11:20
10681    14:10
10682    19:15
Name: Arrival_Time, Length: 10682, dtype: object

In [96]:
data['Arrival_Hour']=data['Arrival_Time'].str.split(":").str[0]

In [97]:
data['Arrival_Minute']=data['Arrival_Time'].str.split(":").str[1]

In [98]:
data

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,days,months,years,Arrival_Hour,Arrival_Minute
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10,2h 50m,non-stop,No info,3897,24,3,2019,01,10
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,5,2019,13,15
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25,19h,2 stops,No info,13882,9,6,2019,04,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,12,5,2019,23,30
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,1,3,2019,21,35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107,9,4,2019,22,25
10679,Air India,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145,27,4,2019,23,20
10680,Jet Airways,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229,27,4,2019,11,20
10681,Vistara,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648,1,3,2019,14,10
10682,Air India,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753,9,5,2019,19,15

In [99]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10682 entries, 0 to 10682
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10682 non-null  object
 1   Source           10682 non-null  object
 2   Destination      10682 non-null  object
 3   Route            10682 non-null  object
 4   Dep_Time         10682 non-null  object
 5   Arrival_Time     10682 non-null  object
 6   Duration         10682 non-null  object
 7   Total_Stops      10682 non-null  object
 8   Additional_Info  10682 non-null  object
 9   Price            10682 non-null  int64
 10  days             10682 non-null  int32
 11  months           10682 non-null  int32
 12  years            10682 non-null  int32
 13  Arrival_Hour     10682 non-null  object
 14  Arrival_Minute   10682 non-null  object
dtypes: int32(3), int64(1), object(11)
memory usage: 1.2+ MB

In [100]:
data['Arrival_Hour'] = data.Arrival_Hour.astype(int)
data['Arrival_Minute'] = data.Arrival_Minute.astype(int)

In [101]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10682 entries, 0 to 10682
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10682 non-null  object
 1   Source           10682 non-null  object
 2   Destination      10682 non-null  object
 3   Route            10682 non-null  object
 4   Dep_Time         10682 non-null  object
 5   Arrival_Time     10682 non-null  object
 6   Duration         10682 non-null  object
 7   Total_Stops      10682 non-null  object
 8   Additional_Info  10682 non-null  object
 9   Price            10682 non-null  int64
 10  days             10682 non-null  int32
 11  months           10682 non-null  int32
 12  years            10682 non-null  int32
 13  Arrival_Hour     10682 non-null  int32
 14  Arrival_Minute   10682 non-null  int32
dtypes: int32(5), int64(1), object(9)
memory usage: 1.1+ MB

In [102]:
data.drop('Arrival_Time',axis=1,inplace=True)

In [103]:
data

,Airline,Source,Destination,Route,Dep_Time,Duration,Total_Stops,Additional_Info,Price,days,months,years,Arrival_Hour,Arrival_Minute
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,2h 50m,non-stop,No info,3897,24,3,2019,1,10
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,7h 25m,2 stops,No info,7662,1,5,2019,13,15
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,19h,2 stops,No info,13882,9,6,2019,4,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,5h 25m,1 stop,No info,6218,12,5,2019,23,30
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,4h 45m,1 stop,No info,13302,1,3,2019,21,35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,CCU → BLR,19:55,2h 30m,non-stop,No info,4107,9,4,2019,22,25
10679,Air India,Kolkata,Banglore,CCU → BLR,20:45,2h 35m,non-stop,No info,4145,27,4,2019,23,20
10680,Jet Airways,Banglore,Delhi,BLR → DEL,08:20,3h,non-stop,No info,7229,27,4,2019,11,20
10681,Vistara,Banglore,New Delhi,BLR → DEL,11:30,2h 40m,non-stop,No info,12648,1,3,2019,14,10
10682,Air India,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,8h 20m,2 stops,No info,11753,9,5,2019,19,15

In [104]:
data.columns

Index(['Airline', 'Source', 'Destination', 'Route', 'Dep_Time', 'Duration',
       'Total_Stops', 'Additional_Info', 'Price', 'days', 'months', 'years',
       'Arrival_Hour', 'Arrival_Minute'],
      dtype='object')

In [105]:
data['Dep_Time']

0        22:20
1        05:50
2        09:25
3        18:05
4        16:50
         ...
10678    19:55
10679    20:45
10680    08:20
10681    11:30
10682    10:55
Name: Dep_Time, Length: 10682, dtype: object

In [106]:
data['Dep_hour']=data['Dep_Time'].str.split(":").str[0]
data['Dep_mins']=data['Dep_Time'].str.split(":").str[0]

In [107]:
data['Dep_hour'] = data.Dep_hour.astype(int)
data['Dep_mins'] = data.Dep_mins.astype(int)

In [108]:
data.drop('Dep_Time', axis=1, inplace=True)

In [109]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10682 entries, 0 to 10682
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10682 non-null  object
 1   Source           10682 non-null  object
 2   Destination      10682 non-null  object
 3   Route            10682 non-null  object
 4   Duration         10682 non-null  object
 5   Total_Stops      10682 non-null  object
 6   Additional_Info  10682 non-null  object
 7   Price            10682 non-null  int64
 8   days             10682 non-null  int32
 9   months           10682 non-null  int32
 10  years            10682 non-null  int32
 11  Arrival_Hour     10682 non-null  int32
 12  Arrival_Minute   10682 non-null  int32
 13  Dep_hour         10682 non-null  int32
 14  Dep_mins         10682 non-null  int32
dtypes: int32(7), int64(1), object(7)
memory usage: 1.0+ MB

In [110]:
data.Total_Stops

0        non-stop
1         2 stops
2         2 stops
3          1 stop
4          1 stop
           ...
10678    non-stop
10679    non-stop
10680    non-stop
10681    non-stop
10682     2 stops
Name: Total_Stops, Length: 10682, dtype: object

In [111]:
data['Total_Stops'].unique()

array(['non-stop', '2 stops', '1 stop', '3 stops', '4 stops'],
      dtype=object)

In [112]:
data['Total_Stops'].isna().sum()

0

In [113]:
data[data['Total_Stops'].isnull()]

Empty DataFrame
Columns: [Airline, Source, Destination, Route, Duration, Total_Stops, Additional_Info, Price, days, months, years, Arrival_Hour, Arrival_Minute, Dep_hour, Dep_mins]
Index: []

In [114]:
data['Total_Stops'].mode()

0    1 stop
Name: Total_Stops, dtype: object

In [115]:
data['Total_Stops'].unique()

array(['non-stop', '2 stops', '1 stop', '3 stops', '4 stops'],
      dtype=object)

In [116]:
data['Total_Stops'] = data['Total_Stops'].map({'non-stop':0, '1 stop':1, '2 stops':2, '3 stops':3, '4 stops':4})

In [117]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10682 entries, 0 to 10682
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10682 non-null  object
 1   Source           10682 non-null  object
 2   Destination      10682 non-null  object
 3   Route            10682 non-null  object
 4   Duration         10682 non-null  object
 5   Total_Stops      10682 non-null  int64
 6   Additional_Info  10682 non-null  object
 7   Price            10682 non-null  int64
 8   days             10682 non-null  int32
 9   months           10682 non-null  int32
 10  years            10682 non-null  int32
 11  Arrival_Hour     10682 non-null  int32
 12  Arrival_Minute   10682 non-null  int32
 13  Dep_hour         10682 non-null  int32
 14  Dep_mins         10682 non-null  int32
dtypes: int32(7), int64(2), object(6)
memory usage: 1.0+ MB

In [118]:
# Route can be used in two ways 
# To know source and destination >> which already in columns of the data 
# as number of stops >> total stops is already there 
# so route is a repeatative information

In [119]:
data.drop('Route', axis=1, inplace=True)

In [120]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10682 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10682 non-null  object
 1   Source           10682 non-null  object
 2   Destination      10682 non-null  object
 3   Duration         10682 non-null  object
 4   Total_Stops      10682 non-null  int64
 5   Additional_Info  10682 non-null  object
 6   Price            10682 non-null  int64
 7   days             10682 non-null  int32
 8   months           10682 non-null  int32
 9   years            10682 non-null  int32
 10  Arrival_Hour     10682 non-null  int32
 11  Arrival_Minute   10682 non-null  int32
 12  Dep_hour         10682 non-null  int32
 13  Dep_mins         10682 non-null  int32
dtypes: int32(7), int64(2), object(5)
memory usage: 959.7+ KB

In [121]:
data['Duration']

0        2h 50m
1        7h 25m
2           19h
3        5h 25m
4        4h 45m
          ...
10678    2h 30m
10679    2h 35m
10680        3h
10681    2h 40m
10682    8h 20m
Name: Duration, Length: 10682, dtype: object

In [122]:
data['Duration_hours'] = data['Duration'].str.split(' ').str[0].str.split('h').str[0]

In [123]:
data['Duration_mins'] = data['Duration'].str.split(' ').str[1].str.split('m').str[0]

In [124]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10682 entries, 0 to 10682
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10682 non-null  object
 1   Source           10682 non-null  object
 2   Destination      10682 non-null  object
 3   Duration         10682 non-null  object
 4   Total_Stops      10682 non-null  int64
 5   Additional_Info  10682 non-null  object
 6   Price            10682 non-null  int64
 7   days             10682 non-null  int32
 8   months           10682 non-null  int32
 9   years            10682 non-null  int32
 10  Arrival_Hour     10682 non-null  int32
 11  Arrival_Minute   10682 non-null  int32
 12  Dep_hour         10682 non-null  int32
 13  Dep_mins         10682 non-null  int32
 14  Duration_hours   10682 non-null  object
 15  Duration_mins    9650 non-null   object
dtypes: int32(7), int64(2), object(7)
memory usage: 1.1+ MB

In [125]:
data.drop('Duration', axis=1, inplace=True)

In [126]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10682 entries, 0 to 10682
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10682 non-null  object
 1   Source           10682 non-null  object
 2   Destination      10682 non-null  object
 3   Total_Stops      10682 non-null  int64
 4   Additional_Info  10682 non-null  object
 5   Price            10682 non-null  int64
 6   days             10682 non-null  int32
 7   months           10682 non-null  int32
 8   years            10682 non-null  int32
 9   Arrival_Hour     10682 non-null  int32
 10  Arrival_Minute   10682 non-null  int32
 11  Dep_hour         10682 non-null  int32
 12  Dep_mins         10682 non-null  int32
 13  Duration_hours   10682 non-null  object
 14  Duration_mins    9650 non-null   object
dtypes: int32(7), int64(2), object(6)
memory usage: 1.0+ MB

In [127]:
data['Additional_Info'].unique()

array(['No info', 'In-flight meal not included',
       'No check-in baggage included', '1 Short layover', 'No Info',
       '1 Long layover', 'Change airports', 'Business class',
       'Red-eye flight', '2 Long layover'], dtype=object)

In [128]:
data[["Airline","Source","Destination","Additional_Info"]]

           Airline    Source Destination Additional_Info
0           IndiGo  Banglore   New Delhi         No info
1        Air India   Kolkata    Banglore         No info
2      Jet Airways     Delhi      Cochin         No info
3           IndiGo   Kolkata    Banglore         No info
4           IndiGo  Banglore   New Delhi         No info
...            ...       ...         ...             ...
10678     Air Asia   Kolkata    Banglore         No info
10679    Air India   Kolkata    Banglore         No info
10680  Jet Airways  Banglore       Delhi         No info
10681      Vistara  Banglore   New Delhi         No info
10682    Air India     Delhi      Cochin         No info

[10682 rows x 4 columns]

In [129]:
# all of the above categorical data is nominal data, so we will be using one hot encoding
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder()
encoder

OneHotEncoder()

In [130]:
encoder.fit_transform(data[["Airline","Source","Destination","Additional_Info"]]).toarray()
encoder.get_feature_names_out()

array(['Airline_Air Asia', 'Airline_Air India', 'Airline_GoAir',
       'Airline_IndiGo', 'Airline_Jet Airways',
       'Airline_Jet Airways Business', 'Airline_Multiple carriers',
       'Airline_Multiple carriers Premium economy', 'Airline_SpiceJet',
       'Airline_Trujet', 'Airline_Vistara',
       'Airline_Vistara Premium economy', 'Source_Banglore',
       'Source_Chennai', 'Source_Delhi', 'Source_Kolkata',
       'Source_Mumbai', 'Destination_Banglore', 'Destination_Cochin',
       'Destination_Delhi', 'Destination_Hyderabad',
       'Destination_Kolkata', 'Destination_New Delhi',
       'Additional_Info_1 Long layover',
       'Additional_Info_1 Short layover',
       'Additional_Info_2 Long layover', 'Additional_Info_Business class',
       'Additional_Info_Change airports',
       'Additional_Info_In-flight meal not included',
       'Additional_Info_No Info',
       'Additional_Info_No check-in baggage included',
       'Additional_Info_No info', 'Additional_Info_Red-eye flight'],
      dtype=object)

In [131]:
encode = encoder.fit_transform(data[["Airline","Source","Destination","Additional_Info"]]).toarray()
encoded_data = pd.DataFrame(encode, columns=encoder.get_feature_names_out())

In [132]:
data.drop(['Airline','Source','Destination','Additional_Info'], axis=1, inplace=True)

In [133]:
data

,Total_Stops,Price,days,months,years,Arrival_Hour,Arrival_Minute,Dep_hour,Dep_mins,Duration_hours,Duration_mins
0,0,3897,24,3,2019,1,10,22,22,2,50
1,2,7662,1,5,2019,13,15,5,5,7,25
2,2,13882,9,6,2019,4,25,9,9,19,NaN
3,1,6218,12,5,2019,23,30,18,18,5,25
4,1,13302,1,3,2019,21,35,16,16,4,45
...,...,...,...,...,...,...,...,...,...,...,...
10678,0,4107,9,4,2019,22,25,19,19,2,30
10679,0,4145,27,4,2019,23,20,20,20,2,35
10680,0,7229,27,4,2019,11,20,8,8,3,NaN
10681,0,12648,1,3,2019,14,10,11,11,2,40
10682,2,11753,9,5,2019,19,15,10,10,8,20

In [134]:
encoded_data

,Airline_Air Asia,Airline_Air India,Airline_GoAir,Airline_IndiGo,Airline_Jet Airways,Airline_Jet Airways Business,Airline_Multiple carriers,Airline_Multiple carriers Premium economy,Airline_SpiceJet,Airline_Trujet,...,Additional_Info_1 Long layover,Additional_Info_1 Short layover,Additional_Info_2 Long layover,Additional_Info_Business class,Additional_Info_Change airports,Additional_Info_In-flight meal not included,Additional_Info_No Info,Additional_Info_No check-in baggage included,Additional_Info_No info,Additional_Info_Red-eye flight
0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10677,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
10678,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
10679,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
10680,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
10681,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [136]:
final_data = pd.concat([data,encoded_data], axis=1)
final_data

,Total_Stops,Price,days,months,years,Arrival_Hour,Arrival_Minute,Dep_hour,Dep_mins,Duration_hours,...,Additional_Info_1 Long layover,Additional_Info_1 Short layover,Additional_Info_2 Long layover,Additional_Info_Business class,Additional_Info_Change airports,Additional_Info_In-flight meal not included,Additional_Info_No Info,Additional_Info_No check-in baggage included,Additional_Info_No info,Additional_Info_Red-eye flight
0,0.0,3897.0,24.0,3.0,2019.0,1.0,10.0,22.0,22.0,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,2.0,7662.0,1.0,5.0,2019.0,13.0,15.0,5.0,5.0,7,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,2.0,13882.0,9.0,6.0,2019.0,4.0,25.0,9.0,9.0,19,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1.0,6218.0,12.0,5.0,2019.0,23.0,30.0,18.0,18.0,5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1.0,13302.0,1.0,3.0,2019.0,21.0,35.0,16.0,16.0,4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10679,0.0,4145.0,27.0,4.0,2019.0,23.0,20.0,20.0,20.0,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
10680,0.0,7229.0,27.0,4.0,2019.0,11.0,20.0,8.0,8.0,3,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
10681,0.0,12648.0,1.0,3.0,2019.0,14.0,10.0,11.0,11.0,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
10682,2.0,11753.0,9.0,5.0,2019.0,19.0,15.0,10.0,10.0,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9039,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [137]:
final_data.dtypes

Total_Stops                                     float64
Price                                           float64
days                                            float64
months                                          float64
years                                           float64
Arrival_Hour                                    float64
Arrival_Minute                                  float64
Dep_hour                                        float64
Dep_mins                                        float64
Duration_hours                                   object
Duration_mins                                    object
Airline_Air Asia                                float64
Airline_Air India                               float64
Airline_GoAir                                   float64
Airline_IndiGo                                  float64
Airline_Jet Airways                             float64
Airline_Jet Airways Business                    float64
Airline_Multiple carriers                       float64
Airline_Multiple carriers Premium economy       float64
Airline_SpiceJet                                float64
Airline_Trujet                                  float64
Airline_Vistara                                 float64
Airline_Vistara Premium economy                 float64
Source_Banglore                                 float64
Source_Chennai                                  float64
Source_Delhi                                    float64
Source_Kolkata                                  float64
Source_Mumbai                                   float64
Destination_Banglore                            float64
Destination_Cochin                              float64
Destination_Delhi                               float64
Destination_Hyderabad                           float64
Destination_Kolkata                             float64
Destination_New Delhi                           float64
Additional_Info_1 Long layover                  float64
Additional_Info_1 Short layover                 float64
Additional_Info_2 Long layover                  float64
Additional_Info_Business class                  float64
Additional_Info_Change airports                 float64
Additional_Info_In-flight meal not included     float64
Additional_Info_No Info                         float64
Additional_Info_No check-in baggage included    float64
Additional_Info_No info                         float64
Additional_Info_Red-eye flight                  float64
dtype: object